In [79]:
import numpy as np

In [80]:
import pandas as pd

In [81]:
movies= pd.read_csv('tmdb_5000_movies.csv')
credits= pd.read_csv('tmdb_5000_credits.csv')

In [82]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [83]:
 credits.head(1)['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'],
      dtype=object)

In [84]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [85]:
movies=movies.merge(credits,on='title')

In [86]:
movies.shape

(4809, 23)

In [87]:
movies.shape

(4809, 23)

In [88]:
credits.shape

(4803, 4)

In [89]:
movies['original_language'].value_counts()

en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: original_language, dtype: int64

In [90]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [91]:
#genres
#movies_id
#keywords
#title 
#overview
#cast
#crew

movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [92]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [93]:
#missing
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [94]:
movies.dropna(inplace=True)

In [95]:
movies.duplicated().sum()

0

In [96]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [97]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [98]:
movies['genres']=movies['genres'].apply(convert)

In [99]:
movies['keywords'].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united statesâ€“mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [100]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [101]:
movies['keywords']=movies['keywords'].apply(convert)

In [102]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [103]:
movies['cast'].apply(convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, LÃ©a Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry BishÃ©, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [104]:
movies['cast']=movies['cast'].apply(convert3)

In [105]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [106]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [107]:
movies['crew']=movies['crew'].apply(fetch_director)

In [108]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [109]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [110]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [111]:
#Removing spaces between words

In [112]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [113]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [114]:
movies['tags']=movies['overview']+movies['genres']+movies['cast']+movies['crew']

In [115]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [153]:
new_df=movies[['movie_id','title','tags']]

In [154]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [155]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Dell\AppData\Local\Temp\ipykernel_9736\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [156]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [157]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\Dell\AppData\Local\Temp\ipykernel_9736\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [158]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [159]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver jamescameron'

In [160]:
new_df['tags'][1]

'captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action johnnydepp orlandobloom keiraknightley goreverbinski'

In [173]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000,stop_words='english')

In [174]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [175]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [176]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [177]:
cv.get_feature_names()

D:\AnacondaFiles\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '12th',
 '13',
 '14',
 '15',
 '150',
 '16',
 '17',
 '17th',
 '18',
 '1890',
 '18th',
 '19',
 '1920',
 '1930',
 '1930s',
 '1937',
 '1940',
 '1941',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1977',
 '1979',
 '1980',
 '1980s',
 '1984',
 '1985',
 '1990',
 '1994',
 '1997',
 '1999',
 '19th',
 '20',
 '200',
 '2000',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'abandon',
 'abbi',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abroad',
 'absolut',
 'abus',
 'academ',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'acquir',
 'act',
 'action',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adammckay',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adrift',
 'adult',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'affluent',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aftermath',
 'ag',
 'age',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airborn',
 'aircraft',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanarkin',
 'alaska',
 'alaskan',
 'albert',
 'albertbrook',
 'albertfinney',
 'alcohol',
 'alecbaldwin',
 'alejandrogonzÃ¡leziÃ±Ã¡rritu',
 'alex',
 'alexanderpayn',
 'alexanderskarsgÃ¥rd',
 'alexapenavega',
 'alexia',
 'alexisbledel',
 'alexkendrick',
 'alexpettyf',
 'alexproya',
 'alfi',
 'alfredhitchcock',
 'alfredmolina',
 'algeria',
 'ali',
 'alic',
 'alice',
 'alicebraga',
 'alien',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'alleg',
 'allen',
 'alli',
 'allianc',
 'allies',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandabyn',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'ambassador',
 'amberheard',
 'ambit',
 'ambiti',
 'ambush',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amp',
 'amus',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'ancient',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'andrewadamson',
 'andrewgarfield',
 'andrewniccol',
 'andrzejbartkowiak',
 'andy',
 'andyfickman',
 'andygarcÃ­a',
 'andyserki',
 'andytenn',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annefletch',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'answers',
 'ant',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anti',
 'antic',
 'antiqu',
 'antoinefuqua',
 'anton',
 'antonio',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprentic',
 'approach',
 'approaches',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armiehamm',
 'armor',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'array',
 'arrest',
 'arriv',
 'arrives',
 'arrog',
 'art',
 'arthur',
 'articl',
 'artifici',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assum',
 'astronaut',
 'asylum',
 'athlet',
 'atlant',
 'atom',
 'atomegoyan',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'audreytaut',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'auto',
 'autobiograph',
 'avail',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awesom',
 'awkward',
 'awri',
 'awry',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backyard',
 'bad',
 'bag',
 'bail',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'ban',
 'band',
 'bandit',
 'banish',
 'bank',
 'banker',
 'bar',
 'barbara',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barry',
 'barrylevinson',
 'barrypepp',
 'barrysonnenfeld',
 'bars',
 'bas',
 'base',
 'basebal',
 'basement',
 'basketbal',
 'basketball',
 'batman',
 'battalion',
 'battl',
 'battle',
 'bay',
 'beach',
 'beam',
 'bear',
 'beast',
 'beat',
 'beaten',
 'beau',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'bed',
 'bedroom',
 'bee',
 'befor',
 'befriend',
 'beg',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'beliefs',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'berniemac',
 'best',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'bettemidl',
 'better',
 'betti',
 'bettythoma',
 'beverli',
 'biblic',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bilbo',
 'billcondon',
 'billhad',
 'billi',
 'billion',
 'billionair',
 'billmoseley',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'bind',
 'biograph',
 'biographi',
 'biolog',
 'biologist',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blade',
 'blame',
 'blaze',
 'blend',
 'bless',
 'blind',
 'bliss',
 'block',
 'blood',
 'bloodi',
 'bloodthirsti',
 'bloom',
 'blossom',
 'blow',
 'blu',
 'blue',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bomb',
 'bond',
 'bone',
 'bonniehunt',
 'book',
 'border',
 'bore',
 'boring',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'brazil',
 'break',
 'breakdown',
 'breakup',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'brianlev',
 'brianrobbin',
 'bride',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'brook',
 'brooklyn',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'brucecampbel',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryancranston',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'buri',
 'burn',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butch',
 'butcher',
 'butler',
 'butt',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cain',
 'cal',
 'caleb',
 'california',
 'calm',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'cameroncrow',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campbellscott',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'canin',
 'capabl',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'card',
 'care',
 'career',
 'carefre',
 'careymulligan',
 'cargo',
 'caribbean',
 'carl',
 'carlagugino',
 'carlo',
 'carmen',
 'carol',
 'carolina',
 'carri',
 'carrie',
 'carriefish',
 'cartel',
 'carter',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'castle',
 'cat',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherin',
 'catherinedeneuv',
 'catherinehardwick',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'cattl',
 'caught',
 'caus',
 'cause',
 'cave',
 'cedrictheentertain',
 'celebr',
 'celebration',
 'cell',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channel',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charless',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlott',
 'charm',
 'chart',
 'chase',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chill',
 'china',
 'chines',
 'chip',
 'chiwetelejiofor',
 'chloe',
 'chloÃ«gracemoretz',
 'chloÃ«sevigni',
 'choic',
 'choice',
 'chon',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christoph',
 'christopherguest',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'chuckrussel',
 'church',
 'cia',
 'ciarÃ¡nhind',
 'cillianmurphi',
 'cindi',
 'cinema',
 'circl',
 'circle',
 'circu',
 'circuit',
 'circumst',
 'circumstances',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilization',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'coastal',
 'cocain',
 'cocki',
 'code',
 'codi',
 'cohen',
 'col',
 'cold',
 'cole',
 'colehaus',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'collapse',
 'colleagu',
 'colleague',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collide',
 'collis',
 'colon',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'coming',
 'command',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compound',
 'compromis',
 'compton',
 'compuls',
 'comput',
 'computer',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'connect',
 'connecticut',
 'connel',
 'conni',
 'connienielsen',
 'connor',
 'conquer',
 'conrad',
 'conscience',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contempl',
 'contemporari',
 'contend',
 'content',
 'contest',
 ...]

In [166]:
import nltk

In [135]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in d:\anacondafiles\lib\site-packages (3.7)
Requirement already satisfied: click in d:\anacondafiles\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: tqdm in d:\anacondafiles\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: regex>=2021.8.3 in d:\anacondafiles\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: joblib in d:\anacondafiles\lib\site-packages (from nltk) (1.1.0)
Requirement already satisfied: colorama in d:\anacondafiles\lib\site-packages (from click->nltk) (0.4.5)

In [167]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [168]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [169]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver jamescameron'

In [170]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron'

In [171]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\Dell\AppData\Local\Temp\ipykernel_9736\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [172]:
new_df.head

<bound method NDFrame.head of       movie_id                                     title  \
0        19995                                    Avatar
1          285  Pirates of the Caribbean: At World's End
2       206647                                   Spectre
3        49026                     The Dark Knight Rises
4        49529                               John Carter
...        ...                                       ...
4804      9367                               El Mariachi
4805     72766                                 Newlyweds
4806    231617                 Signed, Sealed, Delivered
4807    126186                          Shanghai Calling
4808     25975                         My Date with Drew

                                                   tags
0     in the 22nd century, a parapleg marin is dispa...
1     captain barbossa, long believ to be dead, ha c...
2     a cryptic messag from bondâ€™ past send him on a...
3     follow the death of district attorney harvey d...
4     john carter is a war-weary, former militari ca...
...                                                 ...
4804  el mariachi just want to play hi guitar and ca...
4805  a newlyw couple' honeymoon is upend by the arr...
4806  "signed, sealed, delivered" introduc a dedic q...
4807  when ambiti new york attorney sam is sent to s...
4808  ever sinc the second grade when he first saw h...

[4806 rows x 3 columns]>

In [178]:
#cosine distance calculation--theta between two vectors

In [179]:
from sklearn.metrics.pairwise import cosine_similarity

In [180]:
cosine_similarity(vectors)

array([[1.        , 0.13957263, 0.08206099, ..., 0.        , 0.        ,
        0.        ],
       [0.13957263, 1.        , 0.08399211, ..., 0.03253   , 0.        ,
        0.03539962],
       [0.08206099, 0.08399211, 1.        , ..., 0.02868877, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03253   , 0.02868877, ..., 1.        , 0.04444444,
        0.02418254],
       [0.        , 0.        , 0.        , ..., 0.04444444, 1.        ,
        0.09673017],
       [0.        , 0.03539962, 0.        , ..., 0.02418254, 0.09673017,
        1.        ]])

In [182]:
similarity=cosine_similarity(vectors)

In [183]:
similarity[0]

array([1.        , 0.13957263, 0.08206099, ..., 0.        , 0.        ,
       0.        ])

In [226]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [190]:
new_df[new_df['title']=='Batman Begins'].index[0]

119

In [219]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 0.9999999999999999),
 (2999, 0.25854384499750954),
 (4405, 0.24618298195866548),
 (61, 0.23262105259961768),
 (1444, 0.2279211529192759),
 (942, 0.22498852128662872),
 (3608, 0.22247460415730486),
 (1194, 0.22227711223719354),
 (1216, 0.22019275302527208),
 (2786, 0.22019275302527208),
 (529, 0.217689644749893),
 (138, 0.2175970699446223),
 (72, 0.21320071635561044),
 (972, 0.21320071635561044),
 (2075, 0.21320071635561044),
 (31, 0.21320071635561041),
 (94, 0.21320071635561041),
 (4348, 0.21320071635561041),
 (2409, 0.2132007163556104),
 (4010, 0.20683507599800763),
 (778, 0.20515248496555452),
 (973, 0.20515248496555452),
 (3999, 0.20515248496555452),
 (4048, 0.2038588765750502),
 (172, 0.20100756305184242),
 (507, 0.19507682662870648),
 (1204, 0.19462473604038072),
 (3730, 0.19284730395996746),
 (322, 0.19069251784911845),
 (495, 0.19069251784911845),
 (2971, 0.18953562637585883),
 (14, 0.18844459036110223),
 (68, 0.18609684207969415),
 (122, 0.18609684207969415),
 (483, 0.18609684207969415),
 (36, 0.18556740475630137),
 (1344, 0.18556740475630137),
 (2372, 0.18556740475630137),
 (2674, 0.1846372364689991),
 (91, 0.18281810603178264),
 (859, 0.18281810603178264),
 (3675, 0.18281810603178264),
 (127, 0.1823262913747181),
 (275, 0.1818181818181818),
 (668, 0.1818181818181818),
 (187, 0.18018749253911176),
 (232, 0.17782168978975482),
 (449, 0.17782168978975482),
 (539, 0.17782168978975482),
 (568, 0.17782168978975482),
 (7, 0.17766726362967533),
 (168, 0.17766726362967533),
 (870, 0.17766726362967533),
 (151, 0.17739371879672478),
 (200, 0.17739371879672478),
 (208, 0.17739371879672478),
 (3083, 0.17739371879672478),
 (931, 0.17407765595569785),
 (1616, 0.17407765595569785),
 (1658, 0.17407765595569785),
 (262, 0.17292861596651865),
 (256, 0.1709408646894569),
 (139, 0.1706971854997297),
 (46, 0.17056057308448835),
 (577, 0.17056057308448835),
 (3152, 0.17056057308448835),
 (27, 0.16796775328675623),
 (2133, 0.16648178955300671),
 (2333, 0.16648178955300671),
 (1201, 0.16514456476895406),
 (2645, 0.16514456476895406),
 (3781, 0.16514456476895406),
 (1004, 0.16412198797244362),
 (2741, 0.16412198797244362),
 (3340, 0.16412198797244362),
 (2148, 0.16116459280507603),
 (3498, 0.16116459280507603),
 (3622, 0.16116459280507603),
 (35, 0.1599005372667078),
 (134, 0.1599005372667078),
 (233, 0.1599005372667078),
 (1488, 0.1599005372667078),
 (3721, 0.1599005372667078),
 (4018, 0.1599005372667078),
 (654, 0.15891043154093204),
 (174, 0.15836151649297914),
 (581, 0.15836151649297914),
 (777, 0.15717365336548286),
 (1089, 0.15627967832118694),
 (26, 0.15569978883230456),
 (111, 0.15569978883230456),
 (121, 0.15569978883230456),
 (300, 0.15569978883230456),
 (2169, 0.15569978883230456),
 (420, 0.1554926033927807),
 (33, 0.15512630699850571),
 (505, 0.15512630699850571),
 (627, 0.15512630699850571),
 (935, 0.15512630699850571),
 (2584, 0.15512630699850571),
 (3621, 0.15512630699850571),
 (149, 0.15386436372416593),
 (311, 0.1531679162134967),
 (678, 0.1531679162134967),
 (937, 0.1531679162134967),
 (150, 0.15289415743128765),
 (467, 0.15228622596829314),
 (1396, 0.15228622596829314),
 (28, 0.15075567228888181),
 (342, 0.15075567228888181),
 (490, 0.15075567228888181),
 (1524, 0.15075567228888181),
 (2161, 0.15075567228888181),
 (3354, 0.15075567228888181),
 (4192, 0.15075567228888181),
 (4673, 0.15075567228888181),
 (166, 0.1507556722888818),
 (582, 0.1507556722888818),
 (1037, 0.1507556722888818),
 (1530, 0.1507556722888818),
 (1920, 0.1507556722888818),
 (2204, 0.1507556722888818),
 (3634, 0.1507556722888818),
 (369, 0.1484539238050411),
 (12, 0.14673479641335552),
 (98, 0.14673479641335552),
 (260, 0.14673479641335552),
 (330, 0.14673479641335552),
 (466, 0.14673479641335552),
 (487, 0.14673479641335552),
 (1109, 0.14673479641335552),
 (1373, 0.14673479641335552),
 (3055, 0.14673479641335552),
 (126, 0.1462544848254261),
 (472, 0.1462544848254261),
 (813, 0.1462544848254261),
 (1297, 0.1462544848254261),
 (1831, 0.1462544848254261),
 (1982, 0.1462544848254261),
 (2450, 0.1462544848254261),
 (3428, 0.1462544848254261),
 (83, 0.14506471329641485),
 (508, 0.14414999403128942),
 (1237, 0.14414999403128942),
 (56, 0.14301938838683884),
 (4, 0.14213381090374028),
 (513, 0.14213381090374028),
 (786, 0.14213381090374028),
 (1195, 0.14213381090374028),
 (1299, 0.14213381090374028),
 (1808, 0.14213381090374028),
 (9, 0.14019992744655632),
 (10, 0.14019992744655632),
 (43, 0.14019992744655632),
 (199, 0.14019992744655632),
 (587, 0.14019992744655632),
 (618, 0.14019992744655632),
 (47, 0.13997312773896353),
 (1, 0.13957263155977062),
 (263, 0.13957263155977062),
 (319, 0.13957263155977062),
 (511, 0.13957263155977062),
 (781, 0.13957263155977062),
 (1077, 0.13957263155977062),
 (1080, 0.13957263155977062),
 (1833, 0.13957263155977062),
 (1942, 0.13957263155977062),
 (1775, 0.13878184541334224),
 (2760, 0.13878184541334224),
 (5, 0.13834289277321493),
 (131, 0.13834289277321493),
 (1401, 0.13834289277321493),
 (3443, 0.13834289277321493),
 (74, 0.13655774839978377),
 (1938, 0.13655774839978377),
 (102, 0.1364877726081535),
 (715, 0.13636363636363635),
 (980, 0.13636363636363635),
 (1329, 0.13636363636363635),
 (1884, 0.13636363636363635),
 (2378, 0.13636363636363635),
 (2396, 0.13636363636363635),
 (2683, 0.13636363636363635),
 (4403, 0.13636363636363635),
 (41, 0.1348399724926484),
 (602, 0.1348399724926484),
 (988, 0.1348399724926484),
 (2072, 0.1348399724926484),
 (2686, 0.1348399724926484),
 (23, 0.1333662673423161),
 (148, 0.1333662673423161),
 (349, 0.1333662673423161),
 (476, 0.1333662673423161),
 (1756, 0.1333662673423161),
 (2323, 0.1333662673423161),
 (2651, 0.1333662673423161),
 (3982, 0.1333662673423161),
 (1965, 0.1332504477222565),
 (234, 0.13318543164240537),
 (1906, 0.13318543164240537),
 (312, 0.1315903389919538),
 (589, 0.1315903389919538),
 (1692, 0.1315903389919538),
 (206, 0.13121597027036946),
 (230, 0.13121597027036946),
 (329, 0.1305582419667734),
 (1082, 0.1305582419667734),
 (1158, 0.1305582419667734),
 (1274, 0.1305582419667734),
 (1280, 0.1305582419667734),
 (182, 0.130051217752471),
 (1233, 0.130051217752471),
 (1537, 0.130051217752471),
 (2820, 0.130051217752471),
 (62, 0.12856486930664499),
 (1276, 0.12856486930664499),
 (1455, 0.12856486930664499),
 (1664, 0.12856486930664499),
 (2445, 0.12856486930664499),
 (4502, 0.12856486930664499),
 (95, 0.12792042981336627),
 (123, 0.12792042981336627),
 (292, 0.12792042981336627),
 (400, 0.12792042981336627),
 (634, 0.12792042981336627),
 (773, 0.12792042981336627),
 (899, 0.12792042981336627),
 (1071, 0.12792042981336627),
 (1086, 0.12792042981336627),
 (1142, 0.12792042981336627),
 (1259, 0.12792042981336627),
 (2053, 0.12792042981336627),
 (2817, 0.12792042981336627),
 (11, 0.12712834523274563),
 (158, 0.12712834523274563),
 (228, 0.12712834523274563),
 (596, 0.12712834523274563),
 (1056, 0.12712834523274563),
 (1305, 0.12712834523274563),
 (2109, 0.12712834523274563),
 (3162, 0.12712834523274563),
 (170, 0.1257389226923863),
 (2448, 0.1257389226923863),
 (152, 0.1254363015010636),
 (236, 0.1254363015010636),
 (784, 0.1254363015010636),
 (920, 0.1254363015010636),
 (1047, 0.1254363015010636),
 (1275, 0.1254363015010636),
 (1383, 0.1254363015010636),
 (412, 0.12439408271422457),
 (572, 0.12439408271422457),
 (17, 0.12309149097933274),
 (1496, 0.12309149097933274),
 (1639, 0.12309149097933274),
 (2106, 0.12309149097933274),
 (2650, 0.12309149097933274),
 (3572, 0.12309149097933274),
 (3720, 0.12309149097933274),
 (4641, 0.12309149097933274),
 (203, 0.12309149097933272),
 (219, 0.12309149097933272),
 (1009, 0.12309149097933272),
 (1096, 0.12309149097933272),
 (1688, 0.12309149097933272),
 (2496, 0.12309149097933272),
 (2865, 0.12309149097933272),
 (3255, 0.12309149097933272),
 (4083, 0.12309149097933272),
 (160, 0.1222789970111296),
 (331, 0.12182898077463451),
 (595, 0.12182898077463451),
 (167, 0.12087344460380703),
 (242, 0.12087344460380703),
 (402, 0.12087344460380703),
 (1306, 0.12087344460380703),
 (1589, 0.12087344460380703),
 (2661, 0.12087344460380703),
 (3805, 0.12087344460380703),
 (84, 0.12060453783110543),
 (143, 0.12060453783110543),
 (217, 0.12060453783110543),
 (403, 0.12060453783110543),
 (3407, 0.12060453783110543),
 (229, 0.11993477322022918),
 (286, 0.11941628680530642),
 (838, 0.1194162868053064),
 (1659, 0.1194162868053064),
 (75, 0.11877113736973435),
 (87, 0.11877113736973435),
 (294, 0.11877113736973435),
 (341, 0.11877113736973435),
 (854, 0.11877113736973435),
 (894, 0.11877113736973435),
 (1015, 0.11877113736973435),
 (1113, 0.11877113736973435),
 (2652, 0.11877113736973435),
 (584, 0.11826247919781652),
 (1321, 0.11826247919781652),
 (1410, 0.11826247919781652),
 (1479, 0.11826247919781652),
 (1783, 0.11826247919781652),
 (2331, 0.11826247919781652),
 (2634, 0.11826247919781652),
 (3728, 0.11826247919781652),
 (16, 0.11677484162422842),
 (207, 0.11677484162422842),
 (455, 0.11677484162422842),
 (794, 0.11677484162422842),
 (922, 0.11677484162422842),
 (960, 0.11677484162422842),
 (1519, 0.11677484162422842),
 (1749, 0.11677484162422842),
 (2060, 0.11677484162422842),
 (2163, 0.11677484162422842),
 (2556, 0.11677484162422842),
 (3322, 0.11677484162422842),
 (3355, 0.11677484162422842),
 (1878, 0.11605177063713189),
 (1534, 0.1149919149152138),
 (2498, 0.1149919149152138),
 (101, 0.11487593716012254),
 (315, 0.11487593716012254),
 (332, 0.11487593716012254),
 (745, 0.11487593716012254),
 (1269, 0.11487593716012254),
 (1301, 0.11487593716012254),
 (1701, 0.11487593716012254),
 (2181, 0.11487593716012254),
 (2253, 0.11487593716012254),
 (3008, 0.11487593716012254),
 (373, 0.11396057645963795),
 (381, 0.11396057645963795),
 (422, 0.11396057645963795),
 (2515, 0.11396057645963795),
 (2856, 0.11396057645963795),
 (2890, 0.11396057645963795),
 (3093, 0.11396057645963795),
 (3374, 0.11396057645963795),
 (3462, 0.11396057645963795),
 (40, 0.11306675421666135),
 (50, 0.11306675421666135),
 (52, 0.11306675421666135),
 (108, 0.11306675421666135),
 (215, 0.11306675421666135),
 (241, 0.11306675421666135),
 (1149, 0.11306675421666135),
 (1623, 0.11306675421666135),
 (1945, 0.11306675421666135),
 (2243, 0.11306675421666135),
 (76, 0.11134044285378084),
 (96, 0.11134044285378084),
 (461, 0.11134044285378084),
 (833, 0.11134044285378084),
 (932, 0.11134044285378084),
 (1161, 0.11134044285378084),
 (3926, 0.11134044285378084),
 (4336, 0.11134044285378084),
 (238, 0.11102547633067379),
 (189, 0.11009637651263604),
 (216, 0.11009637651263604),
 (570, 0.11009637651263604),
 (850, 0.11009637651263604),
 (1254, 0.11009637651263604),
 (1621, 0.11009637651263604),
 (2381, 0.11009637651263604),
 (2854, 0.11009637651263604),
 (3832, 0.11009637651263604),
 (3978, 0.11009637651263604),
 (4568, 0.11009637651263604),
 (4737, 0.11009637651263604),
 (39, 0.10969086361906957),
 (67, 0.10969086361906957),
 (175, 0.10969086361906957),
 (235, 0.10969086361906957),
 (278, 0.10969086361906957),
 (413, 0.10969086361906957),
 (1823, 0.10969086361906957),
 (2035, 0.10969086361906957),
 (2128, 0.10969086361906957),
 (4657, 0.10969086361906957),
 (45, 0.10919021808652281),
 (2256, 0.10919021808652281),
 (1497, 0.10830607221477646),
 (1741, 0.10830607221477646),
 (305, 0.10811249552346706),
 (2916, 0.10811249552346706),
 (4626, 0.10811249552346706),
 (3, 0.10744306187005068),
 (38, 0.10660035817780521),
 (105, 0.10660035817780521),
 (164, 0.10660035817780521),
 (184, 0.10660035817780521),
 (243, 0.10660035817780521),
 (270, 0.10660035817780521),
 (271, 0.10660035817780521),
 (624, 0.10660035817780521),
 (695, 0.10660035817780521),
 (808, 0.10660035817780521),
 (1139, 0.10660035817780521),
 (1178, 0.10660035817780521),
 (1323, 0.10660035817780521),
 (1438, 0.10660035817780521),
 (1673, 0.10660035817780521),
 (1996, 0.10660035817780521),
 (2480, 0.10660035817780521),
 (3155, 0.10660035817780521),
 (3527, 0.10660035817780521),
 (3891, 0.10660035817780521),
 (4011, 0.10660035817780521),
 (4483, 0.10660035817780521),
 (4538, 0.10660035817780521),
 (307, 0.10555008273018728),
 (70, 0.10514994558491725),
 (979, 0.10514994558491725),
 (1293, 0.10514994558491725),
 (1632, 0.10514994558491725),
 (1847, 0.10514994558491725),
 (3874, 0.10514994558491725),
 (4268, 0.10514994558491725),
 (1898, 0.10497277621629558),
 (1282, 0.10418645221412463),
 (93, 0.1037571695799112),
 (334, 0.1037571695799112),
 (740, 0.1037571695799112),
 (1614, 0.1037571695799112),
 (1771, 0.1037571695799112),
 (3102, 0.1037571695799112),
 (3755, 0.1037571695799112),
 (3879, 0.1037571695799112),
 (3907, 0.1037571695799112),
 (88, 0.10341753799900381),
 (109, 0.10341753799900381),
 (159, 0.10341753799900381),
 (249, 0.10341753799900381),
 (537, 0.10341753799900381),
 (866, 0.10341753799900381),
 (995, 0.10341753799900381),
 (1076, 0.10341753799900381),
 (1156, 0.10341753799900381),
 (1348, 0.10341753799900381),
 (1501, 0.10341753799900381),
 (2274, 0.10341753799900381),
 (3072, 0.10341753799900381),
 (3716, 0.10341753799900381),
 (4198, 0.10341753799900381),
 (4279, 0.10341753799900381),
 (4351, 0.10341753799900381),
 (1322, 0.10266540046786907),
 (480, 0.10241831129983783),
 (540, 0.10241831129983783),
 (728, 0.10241831129983783),
 (1121, 0.10241831129983783),
 (2831, 0.10241831129983783),
 (3285, 0.10241831129983783),
 (3212, 0.10144749970923665),
 (59, 0.10120907987385148),
 (790, 0.10120907987385148),
 (19, 0.1011299793694863),
 (106, 0.1011299793694863),
 (279, 0.1011299793694863),
 (410, 0.1011299793694863),
 (419, 0.1011299793694863),
 (473, 0.1011299793694863),
 (1030, 0.1011299793694863),
 (1278, 0.1011299793694863),
 (1523, 0.1011299793694863),
 (1617, 0.1011299793694863),
 (2404, 0.1011299793694863),
 (3091, 0.1011299793694863),
 (3935, 0.1011299793694863),
 (157, 0.10050378152592121),
 (626, 0.10050378152592121),
 (744, 0.10050378152592121),
 (989, 0.10050378152592121),
 (1005, 0.10050378152592121),
 (1092, 0.10050378152592121),
 (1147, 0.10050378152592121),
 (1242, 0.10050378152592121),
 (1334, 0.10050378152592121),
 (1727, 0.10050378152592121),
 (2115, 0.10050378152592121),
 (2218, 0.10050378152592121),
 (2270, 0.10050378152592121),
 (2297, 0.10050378152592121),
 (2326, 0.10050378152592121),
 (3103, 0.10050378152592121),
 (3356, 0.10050378152592121),
 (3396, 0.10050378152592121),
 (4472, 0.10050378152592121),
 (4623, 0.10050378152592121),
 (30, 0.09988907373180403),
 (302, 0.09988907373180403),
 (1367, 0.09988907373180403),
 (2596, 0.09988907373180403),
 (2190, 0.09913631941932194),
 (15, 0.09869275424396534),
 (213, 0.09869275424396534),
 (3620, 0.09869275424396534),
 (22, 0.09782319760890368),
 (205, 0.09782319760890368),
 (209, 0.09782319760890368),
 (244, 0.09782319760890368),
 (259, 0.09782319760890368),
 (276, 0.09782319760890368),
 (547, 0.09782319760890368),
 (762, 0.09782319760890368),
 (800, 0.09782319760890368),
 (1073, 0.09782319760890368),
 (1166, 0.09782319760890368),
 (1365, 0.09782319760890368),
 (1408, 0.09782319760890368),
 (1707, 0.09782319760890368),
 (1770, 0.09782319760890368),
 (2091, 0.09782319760890368),
 (2250, 0.09782319760890368),
 (2521, 0.09782319760890368),
 (2593, 0.09782319760890368),
 (2772, 0.09782319760890368),
 (3347, 0.09782319760890368),
 (4135, 0.09782319760890368),
 (4331, 0.09782319760890368),
 (4542, 0.09782319760890368),
 (4566, 0.09782319760890368),
 (4691, 0.09782319760890368),
 (97, 0.09753841331435326),
 (169, 0.09753841331435326),
 (212, 0.09753841331435326),
 (371, 0.09753841331435326),
 (535, 0.09753841331435326),
 (3225, 0.09753841331435326),
 (3309, 0.09642365197998373),
 (3389, 0.09642365197998373),
 (71, 0.09534625892455922),
 (103, 0.09534625892455922),
 (117, 0.09534625892455922),
 (165, 0.09534625892455922),
 (267, 0.09534625892455922),
 (309, 0.09534625892455922),
 (336, 0.09534625892455922),
 (594, 0.09534625892455922),
 (951, 0.09534625892455922),
 (1099, 0.09534625892455922),
 (1327, 0.09534625892455922),
 (1418, 0.09534625892455922),
 (1474, 0.09534625892455922),
 (1575, 0.09534625892455922),
 (1686, 0.09534625892455922),
 (2241, 0.09534625892455922),
 (2395, 0.09534625892455922),
 (2592, 0.09534625892455922),
 (2762, 0.09534625892455922),
 (2970, 0.09534625892455922),
 (3611, 0.09534625892455922),
 (3994, 0.09534625892455922),
 (4165, 0.09534625892455922),
 (4316, 0.09534625892455922),
 (107, 0.09430419201928972),
 (475, 0.09430419201928972),
 (543, 0.09430419201928972),
 (734, 0.09430419201928972),
 (782, 0.09430419201928972),
 (1457, 0.09430419201928972),
 (2264, 0.09430419201928972),
 (3553, 0.09430419201928972),
 (939, 0.0936072754401818),
 (447, 0.09329556203566843),
 (735, 0.09329556203566843),
 (814, 0.09329556203566843),
 (2903, 0.09329556203566843),
 (3588, 0.09329556203566843),
 (4392, 0.09329556203566843),
 (90, 0.09304842103984708),
 (104, 0.09304842103984708),
 (144, 0.09304842103984708),
 (290, 0.09304842103984708),
 (356, 0.09304842103984708),
 (498, 0.09304842103984708),
 (604, 0.09304842103984708),
 (1240, 0.09304842103984708),
 (1347, 0.09304842103984708),
 (1492, 0.09304842103984708),
 (1560, 0.09304842103984708),
 (1703, 0.09304842103984708),
 (1713, 0.09304842103984708),
 (2259, 0.09304842103984708),
 (2354, 0.09304842103984708),
 (2355, 0.09304842103984708),
 (2731, 0.09304842103984708),
 (4099, 0.09304842103984708),
 (4230, 0.09304842103984708),
 (129, 0.09231861823449955),
 (299, 0.09231861823449955),
 (85, 0.09143006417649888),
 (58, 0.09137173558097589),
 (661, 0.09137173558097589),
 (732, 0.09137173558097589),
 (746, 0.09137173558097589),
 (1019, 0.09137173558097589),
 (1087, 0.09137173558097589),
 (1175, 0.09137173558097589),
 (1220, 0.09137173558097589),
 (78, 0.0909090909090909),
 (237, 0.0909090909090909),
 (358, 0.0909090909090909),
 (368, 0.0909090909090909),
 (1292, 0.0909090909090909),
 (1726, 0.0909090909090909),
 (1860, 0.0909090909090909),
 (2175, 0.0909090909090909),
 (2579, 0.0909090909090909),
 (3195, 0.0909090909090909),
 (3663, 0.0909090909090909),
 (3839, 0.0909090909090909),
 (4045, 0.0909090909090909),
 (4355, 0.0909090909090909),
 (363, 0.09045340337332908),
 (600, 0.09045340337332908),
 (997, 0.09045340337332908),
 (1191, 0.09045340337332908),
 (2052, 0.09045340337332908),
 (3881, 0.09045340337332908),
 (4123, 0.09045340337332908),
 (29, 0.0895622151039798),
 (478, 0.0895622151039798),
 (1273, 0.0895622151039798),
 (3390, 0.0895622151039798),
 (615, 0.08891084489487741),
 (660, 0.08891084489487741),
 (1085, 0.08891084489487741),
 (1137, 0.08891084489487741),
 (1289, 0.08891084489487741),
 (1363, 0.08891084489487741),
 (1364, 0.08891084489487741),
 (1513, 0.08891084489487741),
 (1721, 0.08891084489487741),
 (2090, 0.08891084489487741),
 (3253, 0.08891084489487741),
 (3901, 0.08891084489487741),
 (4061, 0.08891084489487741),
 (4290, 0.08891084489487741),
 (4357, 0.08891084489487741),
 (183, 0.08869685939836239),
 (836, 0.08869685939836239),
 (969, 0.08869685939836239),
 (1011, 0.08869685939836239),
 (1405, 0.08869685939836239),
 (1462, 0.08869685939836239),
 (2363, 0.08869685939836239),
 (3310, 0.08869685939836239),
 (4181, 0.08869685939836239),
 (79, 0.0878561118986134),
 (2439, 0.0878561118986134),
 (2549, 0.0878561118986134),
 (3556, 0.0878561118986134),
 (486, 0.08749572785196141),
 (154, 0.08703882797784893),
 (245, 0.08703882797784893),
 (362, 0.08703882797784893),
 (1032, 0.08703882797784893),
 (1241, 0.08703882797784893),
 (1469, 0.08703882797784893),
 (1471, 0.08703882797784893),
 (1606, 0.08703882797784893),
 (1719, 0.08703882797784893),
 (2309, 0.08703882797784893),
 (2957, 0.08703882797784893),
 (3133, 0.08703882797784893),
 (3635, 0.08703882797784893),
 (3770, 0.08703882797784893),
 (3851, 0.08703882797784893),
 (4079, 0.08703882797784893),
 (4256, 0.08703882797784893),
 (4490, 0.08703882797784893),
 (491, 0.08703882797784891),
 (768, 0.08703882797784891),
 (2135, 0.08703882797784891),
 (3560, 0.08624393618641035),
 (3905, 0.08624393618641035),
 (48, 0.08547043234472845),
 (1202, 0.08547043234472845),
 (82, 0.08528028654224418),
 (196, 0.08528028654224418),

In [228]:
recommend('Batman Begins')

Synecdoche, New York
10th & Wolf
American Psycho
Sexy Beast
Copying Beethoven

In [214]:
new_df.iloc[2252].title

'Synecdoche, New York'

In [215]:
new_df.iloc[3297].title

'10th & Wolf'

In [216]:
new_df.iloc[2960].title

'Copying Beethoven'

In [217]:
new_df.iloc[3261].title

'American Psycho'

In [209]:
new_df.iloc[3732].title

'Sexy Beast'

In [231]:
recommend('Spectre')

Quantum of Solace
Never Say Never Again
From Russia with Love
Skyfall
Thunderball

In [232]:
import pickle

In [234]:
pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))